# Generated by Django 3.0.3 on 2020-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='languages',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages',
            field=models.ManyToManyField(to='portfolio.Language'),
        ),
    ]
