# Generated by Django 3.0.3 on 2020-02-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200212_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technology',
            field=models.ManyToManyField(to='portfolio.Technology'),
        ),
    ]
