# Generated by Django 3.0.3 on 2020-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200212_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[(0, 'Machine Learning'), (1, 'Web Development'), (2, 'Other Projects')], default='WB', max_length=2),
        ),
    ]
