# Generated by Django 3.0.3 on 2020-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_portfolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('a', 'Machine Learning'), ('b', 'Web Development'), ('c', 'Other Projects')], default='WB', max_length=2),
        ),
    ]
