# Generated by Django 3.0.3 on 2020-02-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200212_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PortfolioType'),
        ),
    ]
