# Generated by Django 3.0.3 on 2020-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200213_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
