# Generated by Django 3.0.3 on 2020-02-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotype',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
