# Generated by Django 3.0.3 on 2020-02-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_portfoliotype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
