name: Node CI

on:
  push:
    branches:
      -react-src

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@react-src
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm install
    # - run: npm run build --if-present
    # - run: npm test
      env:
        BRANCH: master
        BUILD_SCRIPT: npm install && npm run build
        CI: true
